services:
  postgres-db:
    container_name: todo
    image: postgres # use latest official postgres version
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: chuma
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5434:5432" # 5434 (external port - public facing) 5432 (internal port - private facing listener...)

volumes:
  postgresql_data:
    driver: local