spring:
  application:
    name: todo

  datasource:
    url: jdbc:postgresql://localhost:9999/todo
    driver-class-name: org.postgresql.Driver
    username: chuma
    password: password

  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    # this specifies the location of where we created our flyway setup
    locations: classpath:db/migration

server:
  port: 8080
