
-- Removing so that I don't have to worry about the database auto incrementing by 50.
-- CREATE SEQUENCE IF NOT EXISTS task_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE category
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     modified to TEXT because this dynamically sizes for us!
    label TEXT,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE task
(
    id          BIGINT NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    is_complete BOOLEAN,
    category_id BIGINT,
    CONSTRAINT pk_task PRIMARY KEY (id)
);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);